[package]
name = "r03-knock-knock-interrupt"
version = "0.1.0"
authors = ["David (DDT) Tillemans <david.tillemans@cryptable.org>"]
edition = "2018"

[dependencies]


[features]
raspi3 = []
raspi4 = []